# Generated by Django 5.2 on 2026-03-27 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('scoop_type', models.CharField(choices=[('cone', 'Cone'), ('cup', 'Cup'), ('bar', 'Bar'), ('sandwich', 'Sandwich'), ('sundae', 'Sundae')], default='cone', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_sugar_free', models.BooleanField(default=False)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoops', to='scoop.flavour')),
            ],
        ),
        migrations.CreateModel(
            name='ScoopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scoops/')),
                ('scoop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scoop.scoop')),
            ],
        ),
    ]
