# Generated by Django 5.2 on 2026-03-27 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrostyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frosty_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartScoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scoop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoop.scoop')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoops', to='frostycart.frostycart')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cart', 'scoop'), name='unique_cart_scoop')],
            },
        ),
    ]
